workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.perfex.admin"
        CERTIFICATE_PASSWORD: "debbere"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Archive app
        script: |
          flutter build ios --release --no-codesign
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa
    artifacts:
      - build/**/**/*.ipa
      - build/**/**/*.xcarchive
