workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.perfex.admin
        CERTIFICATE_PASSWORD: debbere
      ios_signing:
        certificate: iOS  # <- nome esatto caricato su Codemagic
        certificate_password: debbere
        provisioning_profile: Horizone_AdHoc_Profile # <- nome esatto caricato su Codemagic

    scripts:
      - name: Clean build
        script: |
          flutter clean
      - name: Get packages
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - deboratraini@gmail.com
