workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      ios_signing:
        certificates:
          - certificate_id: ios           # Nome del certificato .p12 caricato su Codemagic
            certificate_password: debbere # Password del file .p12
        provisioning_profiles:
          - bundle_id: com.perfex.admin   # Bundle ID della tua app
            name: Horizone_AdHoc_Profile  # Nome del provisioning profile caricato su Codemagic
            target: Runner
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa

