workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      ios_signing:
        certificates:
          Runner: # ⬅️ Questo è il nome del target
            certificate_id: "IOS" # copia da Codemagic > Certificates
            certificate_password: "debbere"       # password del .p12
        provisioning_profiles:
          Runner:
            bundle_id: "com.perfex.admin"
            name: "Horizone_AdHoc_Profile"
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
