workflows:
  ios-release-build:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      vars:
        BUNDLE_ID: com.perfex.admin      # <-- SOSTITUISCI con il tuo vero Bundle ID
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        certificates:
          - certificate: ios_distribution.p12
            password: "debbere"  # <-- SOSTITUISCI con la password .p12
            name: ios
            type: distribution
            source: file
            group: debug
            filePath: certificates/ios_distribution.p12
        provisioning_profiles:
          - name: ios_provisioning_profile
            type: ad-hoc
            source: file
            group: debug
            filePath: profiles/Horizone_AdHocmobileprovision.mobileprovision
    triggering:
      events:
        - push
    scripts:
      - name: Build IPA
        script: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
