workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.perfex.admin"
        CERTIFICATE_PASSWORD: "debbere"
    ios_signing:
      certificates:
        - $IOS_CERTIFICATE
      provisioning_profiles:
        - $IOS_PROVISIONING_PROFILE
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa


