workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      ios_signing:
        certificates:
          - certificate_id: IOS # es: ios_distribution_cert
            certificate_password: debbere
        provisioning_profiles:
          - profile_reference: Horizone_AdHoc_Profile  # es: Horizone_Admin_Profile
            bundle_id: com.perfex.admin                   # bundle ID esatto registrato su Apple
            target: Runner
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa

