workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      vars:
        APP_ID: "com.perfex.admin"
        BUNDLE_ID: "com.perfex.admin"
        CERTIFICATE_PASSWORD: "debbere"
      ios_signing:
        certificates:
          - certificate_id: ios
            password: debbere
        provisioning_profiles:
          - profile: Horizone_AdHoc_Profile.mobileprovision
            bundle_id: com.perfex.admin
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ipa --release --export-options-plist=ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
