workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      vars:
        FLUTTER_BUILD_MODE: release
      ios_signing:
        certificates:
          - certificate_id: "abcd1234-5678-90ef-ghij-klmnopqrstuv" # <-- tuo certificato
            certificate_password: "debbere"
        provisioning_profiles:
          - name: "Horizone_AdHoc_Profile" # <-- nome profilo su Codemagic
            bundle_id: "com.perfex.admin" # <-- tuo vero bundle ID
            target: "Runner" # <-- importante! specifica il target
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa