workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      vars:
        BUNDLE_ID: "com.perfex.admin"
        CERTIFICATE_PASSWORD: "debbere"
      ios_signing:
        certificates:
          - name: ios_distribution
            certificate: >
              <INCOLLA QUI IL CONTENUTO DI p12.txt TUTTO SU UNA RIGA>
            password: $CERTIFICATE_PASSWORD
        provisioning_profiles:
          - name: ios_provisioning
            profile: >
              <INCOLLA QUI IL CONTENUTO DI mobileprovision.txt TUTTO SU UNA RIGA>
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build ipa
        script: |
          flutter build ipa --release --export-options-plist=ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
