workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        certificates:
          - filePath: ios_signing/ios_distribution.p12
            password: debbere
        provisioning_profiles:
          - filePath: ios_signing/Horizone_AdHoc_Profile.mobileprovision
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/**/**/*.ipa
      - build/**/**/*.xcarchive


