workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      ios_signing:
        certificates:
          - certificate_id: "IOS"
            certificate_password: "debbere"
            # 🔽 Collega al target Runner qui sotto
            target: "Runner"
        provisioning_profiles:
          Runner:
            bundle_id: "com.perfex.admin"
            name: "Horizone_AdHoc_Profile"
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
