workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      vars:
        BUNDLE_ID: "com.perfex.admin"
        CERTIFICATE_PASSWORD: "debbere"
      ios_signing:
        certificates:
          - iOS
        provisioning_profiles:
          - Horizone_AdHoc_Profile
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build ipa
        script: |
          flutter build ios --release --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
