workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      ios_signing:
        certificates:
          - certificate_id: IOS          # <-- Nome del certificato p12 caricato
            certificate_password: debbere             # <-- Password del file .p12
        provisioning_profiles:
          - profile_reference: Horizone_AdHoc_Profile # <-- Nome esatto del provisioning profile caricato
            bundle_id: com.perfex.admin               # <-- Bundle ID della tua app iOS
            target: Runner                            # <-- Nome del target Xcode (di solito "Runner")
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa

