workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      vars:
        BUNDLE_ID: "com.perfex.admin"
      ios_signing:
        certificates:
          - certificate: $IOS_CERTIFICATE
            password: $CERTIFICATE_PASSWORD
            type: distribution
        provisioning_profiles:
          - name: Horizone_AdHoc_Profile
            profile: $IOS_PROVISIONING_PROFILE
            type: ad-hoc
            bundle_id: "com.perfex.admin"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
