workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      ios_signing:
        certificates:
          - certificate_id: ios
            certificate_password: debbere
        provisioning_profiles:
          - bundle_id: com.perfex.admin
            profile_reference: Horizone_AdHoc_Profile
            target: Runner
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa


