workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      ios_signing:
        certificates:
          - certificate_id: "abcd1234-5678-90ef-ghij-klmnopqrstuv" # <-- ID certificato .p12
            certificate_password: "TUA_PASSWORD_DEL_P12"
        provisioning_profiles:
          - bundle_id: "com.horizone.perfex" # <-- Tuo Bundle ID registrato
            name: "Horizone_AdHoc_Profile"   # <-- Nome esatto del provisioning su Codemagic
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
